server:
  port: 8000
  mode: 'release'
  limitNum: 20
  #是否使用mongo
  useMongo: false
  # 是否使用redis
  useRedis: false

redis:
  Addr: '127.0.0.1:6379'
  password: '123456'
  db: 0

mysql:
  user: root
  password: '123456'
  path: '127.0.0.1:3306'
  database: 'user-center'
  config: 'charset=utf8&parseTime=True&loc=Local'
  driver: 'mysql'
  maxIdleConns: 10
  maxOpenConns: 100
  log: true

mongo:
  database: ''
  url: ''

session:
  key: ' USER_SECRET'
  size: 10
  # 7 * 86400 7天
  maxAge: 604800
  path: '/'
  domain: ''
  httpOnly: true

log:
  debug: true
  maxAge: 7
  fileName: 'server.log'
  dirName: '/data/gin-user-center/logs'
  
url:
  prefix: '/api/v1/gin-user-center'